FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./

COPY . .

RUN npm install

RUN npm run build

##############################################

FROM node:22-alpine AS production

WORKDIR /app

COPY --from=build /dist/ ./dist

EXPOSE 3000

CMD ["npm", "start"]